### ISSUE TITLE
Release 2.0.5 as stable

### ISSUE THREAD

**Issue by helmesjo** [gasuketsu/conan-fakeit#5]
If everything seems good, could you release stable/2.0.5? 

Only one small note: 
 * README is still missing the `nunit` example under **[Options](https://github.com/gasuketsu/conan-fakeit/blob/develop/README.md#options)**.
 * Also please fix the badges to that they correctly link to travis.

Thanks!

**Comment by gasuketsu** [comment]
Sure, I will do that this weekend.

**Comment by gasuketsu** [comment]
Released.
